// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHw2BDgiCHdd2-dsftfLpqURG3yVhGICU',
    appId: '1:45377749198:web:271adbd564a50528c2509f',
    messagingSenderId: '45377749198',
    projectId: 'collegeeventsbooking',
    authDomain: 'collegeeventsbooking.firebaseapp.com',
    storageBucket: 'collegeeventsbooking.appspot.com',
    measurementId: 'G-S6LYK14C21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ihye94WWpsfMdTaWgp_1xstVNZbvQaY',
    appId: '1:45377749198:android:a4cc582149113d91c2509f',
    messagingSenderId: '45377749198',
    projectId: 'collegeeventsbooking',
    storageBucket: 'collegeeventsbooking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcH4RDdEdpsQTtGacQoJC8L5p8ATjRnTM',
    appId: '1:45377749198:ios:a0fc547725a8fa70c2509f',
    messagingSenderId: '45377749198',
    projectId: 'collegeeventsbooking',
    storageBucket: 'collegeeventsbooking.appspot.com',
    iosBundleId: 'com.example.collegeEvents',
  );
}
